def find_pos_motif(s, t):
    pos_ls = []
    len_t = len(t)
    len_s = len(s)
    for index in range(0, len_s):
        sub_s = s[index : index+len_t]
        if t == sub_s:
            pos_ls.append(str(index+1))
    
    print(' '.join(pos_ls))


find_pos_motif(
    'GGTTTCCAGGGGCGTTTCCAACCCAGTTTCCACGTTTCCAGTTTCCATAGACCCGTTTCCATACTAGTTTCCAGCCGTGGGTTTCCACGGTTTCCAACAGTTTCCAAGTTTCCAGTTTCCATAGTTTCCAGTTTCCATTTGTTTCCAGAGGTTTCCACTTTTGTTTCCAGTTTCCAAAAAAGGGTTTCCAAGGTTTCCATCGCTGGTTTCCAGCGTTTCCATGTTTCCATGTGTTTCCAGCACCTAGTTTCCATATGTTTCCATCAGTTGTTTCCATTGCTGTTTCCAAAGTTTCCACTCGTCTAAACCCAGTTTCCACGTTTCCAATTATGGAGTTTCCAGAAAGGGGTTTCCAGTTTCCAGGTGGTTTCCAAGTGTTTCCACCGTTTCCAGCGAATAGTTTCCAACGCTTGTTTCCAGTTTCCAGTTTCCAGTTTCCAGGTTTCCAACGTTTCCAGTTTCCATACAAGTTGTCCGTTTCCAGTGGCATGTTTCCAGTTTCCAGCGGTTTCCAAAATCGTTTCCATCAGAATCGGTTTCCATGTTTCCATAAGCGTTTCCACAATTGTTTCCAGTTTCCATGTTTCCATCGGATGTTTCCATGTTTCCAGAATAAGTTTCCAGTTTCCAGGTGTTTCCAGTTTCCATGTTCGTTTCCAAGTTTCCATCGTTTCCACAGTTTCCAATGTTTCCAGTTTCCACGCGCGTTTCCAAGGGTTTCCAGAGTTTCCATAGGGGTTTCCAGTTTCCAGTTTCCAATGTTTCCACGTTTCCATTGACGTTTCCACTGCTACATGCACGGTTTCCAGAAAGCTTCGTTTCCAGTTTCCAAGTTTCCATTCGG',
    'GTTTCCAGT'
)